### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/messagebird#1]
Ping me when you're done writing the code and readme, then I'll do a code review.

**Comment by petericebear** [comment]
I will Freek. This evening I will place the code online.

**Comment by freekmurze** [comment]
Code review done. If I've done anything you don't like, let me know.

Could you add some setup instructions in the readme?

**Comment by petericebear** [comment]
I added some testing and some setup instructions.

**Comment by freekmurze** [comment]
Great thanks!
