### ISSUE TITLE
Packagist isn't updating

### ISSUE THREAD

**Issue by erikgaal** [laravel-notification-channels/messagebird#23]
Hi there,

It looks like packagist.org isn't updating this package properly. It still reports `v1.0.2` as the latest. Have you configured the webhooks for this repo?

**Comment by petericebear** [comment]
Hmm, I do not have rights for that. @themsaid can you set up the webhook for me? I see you are the maintainer on packagist for the namespace.

**Comment by petericebear** [comment]
Or can @freekmurze help out also?

**Comment by erikgaal** [comment]
It's updated now to `v2.0.0`, but maybe this still needs to be checked for future updates.

**Comment by atymic** [comment]
I think this is an issue for other repos as well. Maybe the org needs to be re-linked?

**Comment by atymic** [comment]
cc @themsaid @freekmurze 

I don't actually have access to packagist so I can't help unfortunately.

**Comment by atymic** [comment]
Also an issue here:
https://github.com/laravel-notification-channels/apn/issues/62

**Comment by atymic** [comment]
Github hooks should be syncing with packagist properly now. If there are any issues in the future ping me 😄
