### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/messagebird#31]
Laravel 8 has been released today and we need to update this repo to support it.
See https://laravel.com/docs/8.x/upgrade & https://github.com/laravel-notification-channels/channels/issues/107

**Comment by petericebear** [comment]
I will try to update this today or one of the upcoming days. Have a packed schedule at the moment.

**Comment by atymic** [comment]
No worries :)

**Comment by petericebear** [comment]
Picking that up as we speak. Thanks!
